LoC
RoyPy/15201-bogush pull request #1
Opened 2017-02-25 12:33 UTC by RoyPy

Implement working task solution

2017-03-31 04:42 UTC, levanovd requested changes
На конфиге
```
  .h  
  
```
выдает
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at loc.filter.FilterFactory.createByString(Unknown Source)
	at loc.filter.FilterFactory.create(Unknown Source)
	at loc.ConfigFileReader.readFilters(Unknown Source)
	at loc.Main.main(Unknown Source)
```

2017-03-31 04:42 UTC, levanovd commented on LoC/src/loc/statistics/StatisticsComparator.java
> +	public int compare(Map.Entry<Filter, FileStatistics> o1, Map.Entry<Filter, FileStatistics> o2) {
Надо поддержать равенство тоже:

` The ordering imposed by a comparator c on a set of elements S is said to be consistent with equals if and only if c.compare(e1, e2)==0 has the same boolean value as e1.equals(e2) for every e1 and e2 in S.`

2017-03-31 04:42 UTC, levanovd commented on LoC/src/loc/statistics/StatisticsSerializer.java
> +	public static char space              = ' ';
`public static final SPACE`

2017-04-07 03:13 UTC, levanovd commented
```
compile:
    [javac] Compiling 32 source files to /home/levanov/NSU/oop2/15201-bogush/LoC/out/classes
    [javac] /home/levanov/NSU/oop2/15201-bogush/LoC/src/loc/filter/FilterFactory.java:3: error: package com.sun.javaws.exceptions does not exist
    [javac] import com.sun.javaws.exceptions.InvalidArgumentException;
    [javac]                                 ^
    [javac] 1 error
```

2017-04-07 04:08 UTC, RoyPy commented
Fixed
> On Apr 7, 2017, at 10:13 AM, levanovd <notifications@github.com> wrote:
> 
> compile:
>     [javac] Compiling 32 source files to /home/levanov/NSU/oop2/15201-bogush/LoC/out/classes
>     [javac] /home/levanov/NSU/oop2/15201-bogush/LoC/src/loc/filter/FilterFactory.java:3: error: package com.sun.javaws.exceptions does not exist
>     [javac] import com.sun.javaws.exceptions.InvalidArgumentException;
>     [javac]                                 ^
>     [javac] 1 error
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/RoyPy/15201-bogush/pull/1#issuecomment-292416221>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ANa_ViROOIKkHTv37B6CNn2vJU-6BRekks5rtanHgaJpZM4ML_-l>.
>

2017-04-07 04:10 UTC, levanovd commented
```
java.lang.ClassCastException: Cannot cast loc.filter.filters.aggregate.Or to loc.filter.filters.aggregate.And
	at java.lang.Class.cast(Class.java:3369)
	at loc.filter.serializers.aggregate.OrFilterSerializer.serialize(Unknown Source)
	at loc.statistics.StatisticsSerializer.serialize(Unknown Source)
	at loc.Main.main(Unknown Source)
```

2017-04-07 04:49 UTC, RoyPy commented
Fixed and added some new tests
> On Apr 7, 2017, at 11:10 AM, levanovd <notifications@github.com> wrote:
> 
> java.lang.ClassCastException: Cannot cast loc.filter.filters.aggregate.Or to loc.filter.filters.aggregate.And
> 	at java.lang.Class.cast(Class.java:3369)
> 	at loc.filter.serializers.aggregate.OrFilterSerializer.serialize(Unknown Source)
> 	at loc.statistics.StatisticsSerializer.serialize(Unknown Source)
> 	at loc.Main.main(Unknown Source)
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/RoyPy/15201-bogush/pull/1#issuecomment-292428905>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ANa_Vqz4qenrwUeKuo3FFdPT2I_eS87gks5rtbdAgaJpZM4ML_-l>.
>

2017-04-28 03:28 UTC, levanovd commented
Почему-то просто .cpp получилось больше, чем ".cpp или что-то еще"
```
Total - 9358226 lines in 19868 files
---------------------
.cpp                  - 11649272 lines in 14804 files
|(.cpp .h .hpp .java) - 9358226  lines in 19868 files
|(.cpp .h .hpp)       - 9308830  lines in 19702 files
|(.cpp .h)            - 9280681  lines in 19537 files
&(.cpp >1400000000)   - 5824636  lines in 7402  files
.h                    - 3456045  lines in 12135 files
.java                 - 49396    lines in 166   files
.hpp                  - 28149    lines in 165   files
```

2017-05-05 04:09 UTC, levanovd approved these changes

2017-05-05 04:09 UTC, levanovd commented
Принимается

2017-05-31 04:27 UTC, merged